version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_users
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - kubernate-course
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: msvc_courses
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - kubernate-course

  msvc-users:
    container_name: msvc-users
    image: janielhernandez/users:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-users/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_users
      DB_USERNAME: root
      DB_PASSWORD: sasa
      courses_URL: msvc-courses:8002
    networks:
      - kubernate-course
    depends_on:
      - mysql8

  msvc-courses:
    container_name: msvc-courses
    image: janielhernandez/courses:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-courses/Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_courses
      DB_USERNAME: postgres
      DB_PASSWORD: sasa
      USER_URL: msvc-users:8001
    networks:
      - kubernate-course
    depends_on:
      - postgres14
      - msvc-users
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  kubernate-course:
    name: kubernate-course
