server:
  port: 5000


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: elevator_calls
      username: root
      password: "sasa"
      authentication-database: admin
  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer